import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface PDFStudentInfo {
  name: string;
  admissionNumber: string;
  program: string;
  department?: string;
  school?: string;
  yearOfStudy: number;
  semesterNumber: number;
  status?: string;
}

export interface PDFCourseGrade {
  courseCode: string;
  courseTitle: string;
  creditHours: number;
  catScore: number;
  examScore: number;
  totalScore: number;
  letterGrade: string;
  gradePoint: number;
}

export interface PDFSemesterResult {
  semesterLabel: string;
  academicYear: string;
  courses: PDFCourseGrade[];
  gpa: number;
  creditsEarned: number;
}

export interface PDFTransaction {
  date: string;
  reference: string;
  description: string;
  method: string;
  amount: number;
  status: string;
}

const UNIVERSITY_HEADER = {
  name: 'ZETECH UNIVERSITY',
  motto: 'Invent Your Future',
  address: 'P.O. Box 2768 - 00200, Nairobi, Kenya',
  contact: 'Tel: +254 719 034 500 | Email: info@zetech.ac.ke | Web: www.zetech.ac.ke',
};

// Colors (Oxford Navy & University Gold)
const NAVY = [15, 23, 42]; // #0f172a
const GOLD = [217, 119, 6]; // #d97706
const SLATE = [100, 116, 139]; // #64748b

/**
 * Adds University Header & Crest Banner
 */
function addHeader(doc: jsPDF, title: string) {
  // Top Banner
  doc.setFillColor(NAVY[0], NAVY[1], NAVY[2]);
  doc.rect(0, 0, 210, 28, 'F');

  // Gold accent bar
  doc.setFillColor(GOLD[0], GOLD[1], GOLD[2]);
  doc.rect(0, 28, 210, 2, 'F');

  // Title text
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text(UNIVERSITY_HEADER.name, 105, 12, { align: 'center' });

  doc.setFont('helvetica', 'italic');
  doc.setFontSize(8);
  doc.text(`"${UNIVERSITY_HEADER.motto}"`, 105, 17, { align: 'center' });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.text(`${UNIVERSITY_HEADER.address} | ${UNIVERSITY_HEADER.contact}`, 105, 23, { align: 'center' });

  // Document Title Banner
  doc.setTextColor(NAVY[0], NAVY[1], NAVY[2]);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.text(title.toUpperCase(), 105, 38, { align: 'center' });

  // Thin separator under title
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.5);
  doc.line(14, 42, 196, 42);
}

/**
 * Adds Footer with Date and Page Info
 */
function addFooter(doc: jsPDF, pageNumber: number, totalPages: number) {
  const pageHeight = doc.internal.pageSize.height || 297;
  doc.setDrawColor(226, 232, 240);
  doc.line(14, pageHeight - 15, 196, pageHeight - 15);

  doc.setFont('helvetica', 'italic');
  doc.setFontSize(7);
  doc.setTextColor(SLATE[0], SLATE[1], SLATE[2]);
  const dateStr = new Date().toLocaleString('en-KE', { timeZone: 'Africa/Nairobi' });
  doc.text(`Generated by UAMS Enterprise Core on ${dateStr} EAT • Official Valid Document`, 14, pageHeight - 10);
  doc.text(`Page ${pageNumber} of ${totalPages}`, 196, pageHeight - 10, { align: 'right' });
}

/**
 * 1. Official Academic Transcript PDF
 */
export function generateTranscriptPDF(data: {
  student: PDFStudentInfo;
  semesterResults: PDFSemesterResult[];
  cumulativeGpa: number;
  totalCredits: number;
  academicStanding: string;
}) {
  const doc = new jsPDF('p', 'mm', 'a4');
  addHeader(doc, 'OFFICIAL ACADEMIC TRANSCRIPT');

  // Student Details Box
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(14, 46, 182, 32, 2, 2, 'F');
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(14, 46, 182, 32, 2, 2, 'S');

  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(NAVY[0], NAVY[1], NAVY[2]);

  doc.text('Student Name:', 18, 53);
  doc.setFont('helvetica', 'normal');
  doc.text(data.student.name, 50, 53);

  doc.setFont('helvetica', 'bold');
  doc.text('Admission No:', 120, 53);
  doc.setFont('helvetica', 'normal');
  doc.text(data.student.admissionNumber, 150, 53);

  doc.setFont('helvetica', 'bold');
  doc.text('Program:', 18, 60);
  doc.setFont('helvetica', 'normal');
  doc.text(data.student.program, 50, 60);

  doc.setFont('helvetica', 'bold');
  doc.text('Current Level:', 120, 60);
  doc.setFont('helvetica', 'normal');
  doc.text(`Year ${data.student.yearOfStudy}, Sem ${data.student.semesterNumber}`, 150, 60);

  doc.setFont('helvetica', 'bold');
  doc.text('Cumulative GPA:', 18, 67);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(GOLD[0], GOLD[1], GOLD[2]);
  doc.text(`${data.cumulativeGpa.toFixed(2)} / 4.00`, 50, 67);

  doc.setTextColor(NAVY[0], NAVY[1], NAVY[2]);
  doc.setFont('helvetica', 'bold');
  doc.text('Standing / Honors:', 120, 67);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(16, 149, 100);
  doc.text(data.academicStanding, 150, 67);

  let currentY = 84;

  data.semesterResults.forEach((sem) => {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(NAVY[0], NAVY[1], NAVY[2]);
    doc.text(`${sem.semesterLabel.toUpperCase()} — ${sem.academicYear}`, 14, currentY);

    const tableBody = sem.courses.map((c) => [
      c.courseCode,
      c.courseTitle,
      c.creditHours.toString(),
      c.catScore.toString(),
      c.examScore.toString(),
      c.totalScore.toString(),
      c.letterGrade,
      c.gradePoint.toFixed(1),
    ]);

    autoTable(doc, {
      startY: currentY + 3,
      head: [['Code', 'Course Title', 'Credits', 'CAT (30)', 'Exam (70)', 'Total', 'Grade', 'Points']],
      body: tableBody,
      theme: 'grid',
      headStyles: {
        fillColor: [15, 23, 42],
        textColor: [255, 255, 255],
        fontSize: 8,
        fontStyle: 'bold',
      },
      styles: {
        fontSize: 8,
        cellPadding: 2,
        textColor: [30, 41, 59],
      },
      columnStyles: {
        0: { cellWidth: 24, fontStyle: 'bold' },
        1: { cellWidth: 68 },
        2: { cellWidth: 16, halign: 'center' },
        3: { cellWidth: 16, halign: 'center' },
        4: { cellWidth: 16, halign: 'center' },
        5: { cellWidth: 14, halign: 'center', fontStyle: 'bold' },
        6: { cellWidth: 14, halign: 'center', fontStyle: 'bold' },
        7: { cellWidth: 14, halign: 'center' },
      },
      margin: { left: 14, right: 14 },
    });

    const finalY = (doc as any).lastAutoTable.finalY || currentY + 40;

    // Semester summary line
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(NAVY[0], NAVY[1], NAVY[2]);
    doc.text(`Semester GPA: ${sem.gpa.toFixed(2)}  |  Credits Earned: ${sem.creditsEarned}`, 14, finalY + 5);

    currentY = finalY + 12;
  });

  // Signatures Section
  const pageHeight = doc.internal.pageSize.height || 297;
  const sigY = Math.min(currentY + 10, pageHeight - 40);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(NAVY[0], NAVY[1], NAVY[2]);

  doc.line(18, sigY + 12, 70, sigY + 12);
  doc.text('Registrar (Academic Affairs)', 18, sigY + 16);

  doc.line(140, sigY + 12, 192, sigY + 12);
  doc.text('Dean of Faculty / School', 140, sigY + 16);

  // University Seal Stamp watermark placeholder
  doc.setDrawColor(GOLD[0], GOLD[1], GOLD[2]);
  doc.setLineWidth(1);
  doc.circle(105, sigY + 10, 10, 'S');
  doc.setFontSize(6);
  doc.setTextColor(GOLD[0], GOLD[1], GOLD[2]);
  doc.text('OFFICIAL SEAL', 105, sigY + 11, { align: 'center' });

  addFooter(doc, 1, 1);
  return doc;
}

/**
 * 2. Student Fee Statement PDF
 */
export function generateFeeStatementPDF(data: {
  student: PDFStudentInfo;
  invoiceNumber: string;
  totalBilled: number;
  amountPaid: number;
  balanceRemaining: number;
  dueDate: string;
  transactions: PDFTransaction[];
}) {
  const doc = new jsPDF('p', 'mm', 'a4');
  addHeader(doc, 'STUDENT FINANCIAL STATEMENT');

  // Summary Card
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(14, 46, 182, 34, 2, 2, 'F');
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(14, 46, 182, 34, 2, 2, 'S');

  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(NAVY[0], NAVY[1], NAVY[2]);

  doc.text('Student Name:', 18, 53);
  doc.setFont('helvetica', 'normal');
  doc.text(data.student.name, 50, 53);

  doc.setFont('helvetica', 'bold');
  doc.text('Admission No:', 120, 53);
  doc.setFont('helvetica', 'normal');
  doc.text(data.student.admissionNumber, 150, 53);

  doc.setFont('helvetica', 'bold');
  doc.text('Invoice Ref:', 18, 60);
  doc.setFont('helvetica', 'normal');
  doc.text(data.invoiceNumber, 50, 60);

  doc.setFont('helvetica', 'bold');
  doc.text('Due Date:', 120, 60);
  doc.setFont('helvetica', 'normal');
  doc.text(data.dueDate, 150, 60);

  // Financial Stats
  doc.setFont('helvetica', 'bold');
  doc.text('Total Billed:', 18, 68);
  doc.setFont('helvetica', 'normal');
  doc.text(`KES ${data.totalBilled.toLocaleString()}`, 50, 68);

  doc.setFont('helvetica', 'bold');
  doc.text('Amount Paid:', 80, 68);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(16, 149, 100);
  doc.text(`KES ${data.amountPaid.toLocaleString()}`, 105, 68);

  doc.setTextColor(NAVY[0], NAVY[1], NAVY[2]);
  doc.setFont('helvetica', 'bold');
  doc.text('Outstanding Balance:', 135, 68);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(data.balanceRemaining > 0 ? 220 : 16, data.balanceRemaining > 0 ? 38 : 149, 38);
  doc.text(`KES ${data.balanceRemaining.toLocaleString()}`, 172, 68);

  // Paybill Helper Box
  doc.setFillColor(254, 243, 199);
  doc.roundedRect(14, 84, 182, 12, 1, 1, 'F');
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(180, 83, 9);
  doc.text('Official Payment Instructions: M-Pesa Paybill: 522533  |  Account No: Use Student Admission Number', 18, 91.5);

  // Transactions Table
  const tableBody = data.transactions.map((t) => [
    t.date,
    t.reference,
    t.description,
    t.method.toUpperCase(),
    `KES ${t.amount.toLocaleString()}`,
    t.status.toUpperCase(),
  ]);

  autoTable(doc, {
    startY: 102,
    head: [['Date', 'Reference / Receipt', 'Description', 'Channel', 'Amount', 'Status']],
    body: tableBody,
    theme: 'grid',
    headStyles: {
      fillColor: [15, 23, 42],
      textColor: [255, 255, 255],
      fontSize: 8,
      fontStyle: 'bold',
    },
    styles: {
      fontSize: 8,
      cellPadding: 2.5,
      textColor: [30, 41, 59],
    },
    columnStyles: {
      0: { cellWidth: 28 },
      1: { cellWidth: 35, fontStyle: 'bold' },
      2: { cellWidth: 50 },
      3: { cellWidth: 25 },
      4: { cellWidth: 26, halign: 'right', fontStyle: 'bold' },
      5: { cellWidth: 18, halign: 'center' },
    },
    margin: { left: 14, right: 14 },
  });

  const finalY = (doc as any).lastAutoTable.finalY || 160;

  // Signatures
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(NAVY[0], NAVY[1], NAVY[2]);
  doc.line(18, finalY + 25, 70, finalY + 25);
  doc.text('Bursar / University Finance Officer', 18, finalY + 30);

  addFooter(doc, 1, 1);
  return doc;
}

/**
 * 3. Exam Clearance Card PDF
 */
export function generateExamCardPDF(data: {
  student: PDFStudentInfo;
  semester: string;
  academicYear: string;
  courses: { code: string; title: string; attendancePercent: number }[];
  feeCleared: boolean;
  clearanceCode: string;
}) {
  const doc = new jsPDF('p', 'mm', 'a4');
  addHeader(doc, 'EXAMINATION CLEARANCE CARD');

  // Student Card Info
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(14, 46, 182, 38, 2, 2, 'F');
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(14, 46, 182, 38, 2, 2, 'S');

  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(NAVY[0], NAVY[1], NAVY[2]);

  doc.text('Student Name:', 18, 53);
  doc.setFont('helvetica', 'normal');
  doc.text(data.student.name, 50, 53);

  doc.setFont('helvetica', 'bold');
  doc.text('Admission No:', 120, 53);
  doc.setFont('helvetica', 'normal');
  doc.text(data.student.admissionNumber, 150, 53);

  doc.setFont('helvetica', 'bold');
  doc.text('Program:', 18, 61);
  doc.setFont('helvetica', 'normal');
  doc.text(data.student.program, 50, 61);

  doc.setFont('helvetica', 'bold');
  doc.text('Period:', 120, 61);
  doc.setFont('helvetica', 'normal');
  doc.text(`${data.semester} (${data.academicYear})`, 150, 61);

  doc.setFont('helvetica', 'bold');
  doc.text('Clearance Passcode:', 18, 69);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(GOLD[0], GOLD[1], GOLD[2]);
  doc.text(data.clearanceCode, 50, 69);

  doc.setTextColor(NAVY[0], NAVY[1], NAVY[2]);
  doc.setFont('helvetica', 'bold');
  doc.text('Finance Clearance:', 120, 69);
  doc.setFont('helvetica', 'bold');
  if (data.feeCleared) {
    doc.setTextColor(16, 149, 100);
    doc.text('CLEARED (100% PAID)', 150, 69);
  } else {
    doc.setTextColor(220, 38, 38);
    doc.text('NOT CLEARED (BALANCE DUE)', 150, 69);
  }

  // Course Units Table
  const tableBody = data.courses.map((c) => [
    c.code,
    c.title,
    `${c.attendancePercent}%`,
    c.attendancePercent >= 75 ? 'ELIGIBLE' : 'ATTENDANCE SHORTFALL',
    '________________',
  ]);

  autoTable(doc, {
    startY: 90,
    head: [['Course Code', 'Course Title', 'Attendance', 'Exam Status', 'Invigilator Initial']],
    body: tableBody,
    theme: 'grid',
    headStyles: {
      fillColor: [15, 23, 42],
      textColor: [255, 255, 255],
      fontSize: 8,
      fontStyle: 'bold',
    },
    styles: {
      fontSize: 8,
      cellPadding: 3,
      textColor: [30, 41, 59],
    },
    columnStyles: {
      0: { cellWidth: 26, fontStyle: 'bold' },
      1: { cellWidth: 72 },
      2: { cellWidth: 24, halign: 'center' },
      3: { cellWidth: 32, halign: 'center', fontStyle: 'bold' },
      4: { cellWidth: 28, halign: 'center' },
    },
    margin: { left: 14, right: 14 },
  });

  const finalY = (doc as any).lastAutoTable.finalY || 160;

  // Instructions Box
  doc.setFillColor(241, 245, 249);
  doc.roundedRect(14, finalY + 8, 182, 22, 1, 1, 'F');
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(NAVY[0], NAVY[1], NAVY[2]);
  doc.text('EXAMINATION REGULATIONS & MANDATORY INSTRUCTIONS:', 18, finalY + 14);
  doc.setFont('helvetica', 'normal');
  doc.text('1. Candidates must present this card alongside their University ID to the Chief Invigilator before entering.', 18, finalY + 19);
  doc.text('2. Candidates must achieve at least 75% class attendance and complete all financial obligations to sit for exams.', 18, finalY + 24);

  addFooter(doc, 1, 1);
  return doc;
}

/**
 * 4. PVC Plastic Student ID Card (Front & Back Layout)
 */
export function generateStudentIDCardPDF(data: {
  student: PDFStudentInfo;
  issueDate?: string;
  expiryDate?: string;
}) {
  // CR80 Card Size in Landscape (85.6mm x 54mm)
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: [85.6, 54],
  });

  // ========== FRONT SIDE ==========
  // Background
  doc.setFillColor(255, 255, 255);
  doc.rect(0, 0, 85.6, 54, 'F');

  // Top Navy Bar
  doc.setFillColor(NAVY[0], NAVY[1], NAVY[2]);
  doc.rect(0, 0, 85.6, 12, 'F');

  // Gold Accent Line
  doc.setFillColor(GOLD[0], GOLD[1], GOLD[2]);
  doc.rect(0, 12, 85.6, 1.2, 'F');

  // University Header
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.text('ZETECH UNIVERSITY', 42.8, 6.5, { align: 'center' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(5);
  doc.text('STUDENT IDENTIFICATION CARD', 42.8, 10, { align: 'center' });

  // Student Photo Placeholder Box
  doc.setFillColor(241, 245, 249);
  doc.roundedRect(6, 16, 22, 28, 1, 1, 'F');
  doc.setDrawColor(203, 213, 225);
  doc.roundedRect(6, 16, 22, 28, 1, 1, 'S');

  doc.setFontSize(6);
  doc.setTextColor(SLATE[0], SLATE[1], SLATE[2]);
  doc.text('PHOTO', 17, 30, { align: 'center' });

  // Student Details
  doc.setTextColor(NAVY[0], NAVY[1], NAVY[2]);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7.5);
  doc.text(data.student.name.toUpperCase(), 31, 19);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(6);
  doc.setTextColor(GOLD[0], GOLD[1], GOLD[2]);
  doc.text('ADM NO:', 31, 24);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(NAVY[0], NAVY[1], NAVY[2]);
  doc.setFontSize(7);
  doc.text(data.student.admissionNumber, 44, 24);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(5.5);
  doc.setTextColor(SLATE[0], SLATE[1], SLATE[2]);
  doc.text('PROGRAM:', 31, 29);
  doc.setTextColor(NAVY[0], NAVY[1], NAVY[2]);
  doc.setFont('helvetica', 'normal');
  doc.text(data.student.program, 31, 33, { maxWidth: 50 });

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(5.5);
  doc.setTextColor(SLATE[0], SLATE[1], SLATE[2]);
  doc.text('EXPIRY:', 31, 42);
  doc.setTextColor(NAVY[0], NAVY[1], NAVY[2]);
  doc.setFont('helvetica', 'normal');
  doc.text(data.expiryDate || 'DECEMBER 2027', 43, 42);

  // Bottom Security Strip
  doc.setFillColor(NAVY[0], NAVY[1], NAVY[2]);
  doc.rect(0, 48, 85.6, 6, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(4.5);
  doc.setFont('helvetica', 'normal');
  doc.text('PROPERTY OF ZETECH UNIVERSITY • MUST BE RETURNED UPON DEMAND', 42.8, 52, { align: 'center' });

  // ========== BACK SIDE ==========
  doc.addPage([85.6, 54], 'landscape');

  // Background
  doc.setFillColor(248, 250, 252);
  doc.rect(0, 0, 85.6, 54, 'F');

  // Magnetic / Barcode simulation area
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 5, 85.6, 10, 'F');

  // Terms & Conditions
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(5.5);
  doc.setTextColor(NAVY[0], NAVY[1], NAVY[2]);
  doc.text('CONDITIONS OF ISSUE & USAGE:', 6, 20);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(4.5);
  doc.setTextColor(SLATE[0], SLATE[1], SLATE[2]);
  doc.text('1. This card is non-transferable and remains valid while student is enrolled.', 6, 24);
  doc.text('2. Lost cards must be reported immediately to the Dean of Students office.', 6, 28);
  doc.text('3. If found, please return to any Zetech University campus or police station.', 6, 32);

  // Barcode simulation
  doc.setFillColor(15, 23, 42);
  for (let i = 0; i < 40; i++) {
    const w = (i % 3 === 0 || i % 7 === 0) ? 0.8 : 0.4;
    doc.rect(20 + (i * 1.1), 37, w, 8, 'F');
  }

  doc.setFont('courier', 'bold');
  doc.setFontSize(5);
  doc.setTextColor(NAVY[0], NAVY[1], NAVY[2]);
  doc.text(`*${data.student.admissionNumber}*`, 42.8, 48, { align: 'center' });

  return doc;
}

